ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN;

DROP PROCEDURE IF EXISTS UpdateBestsellerValue;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellerValue()
BEGIN
	DECLARE BOOKRENTS, BR_ID INT;
    DECLARE BESTS BOOLEAN;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_RENTS CURSOR FOR SELECT BOOK_ID FROM RENTS;
    DECLARE ALL_BESTSELLERS CURSOR FOR SELECT BESTSELLER FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_RENTS;
    OPEN ALL_BESTSELLERS;

    WHILE (FINISHED = 0) DO
		FETCH ALL_RENTS INTO BR_ID;
        FETCH ALL_BESTSELLERS INTO BESTS;
		SELECT COUNT(*) FROM RENTS
		WHERE BOOK_ID = BR_ID
		INTO BOOKRENTS;
        IF(BOOKRENTS > 2) THEN
			UPDATE BOOKS SET BESTSELLER = TRUE
            WHERE BOOK_ID = BR_ID;
            COMMIT;
		ELSEIF(BOOKRENTS <= 2) THEN
			UPDATE BOOKS SET BESTSELLER = FALSE
            WHERE BOOK_ID = BR_ID;
            COMMIT;
		ELSEIF(BESTS != true & BESTS != false) THEN
			UPDATE BOOKS SET BESTSELLER = FALSE;
		END IF;
	END WHILE;

    CLOSE ALL_RENTS;
END $$

DELIMITER ;

CALL UpdateBestsellerValue;

SELECT * FROM BOOKS;